language: java
script: mvn install -Ptravis

install: mvn clean install

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - DEV

after_success:
  - mvn clean cobertura:cobertura coveralls:report
